"""
Django settings for datapilot_ai project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
from mongoengine import connect
from decouple import config, Csv
import os

# -------------------------------------------------------------------
# BASE DIRECTORY
# -------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------------------------
# SECURITY
# -------------------------------------------------------------------
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="*", cast=Csv())

# -------------------------------------------------------------------
# MONGOENGINE CONNECTION (for datasets / documents)
# -------------------------------------------------------------------
try:
    connect(
        db=config("MONGO_DB_NAME", default="datapilot"),
        host=config(
            "MONGO_URI",
            default="mongodb+srv://shree:xifko4-higpar-dopgyC@cluster0.fhplq.mongodb.net/datapilot?retryWrites=true&w=majority&appName=Cluster0"
        )
    )
    print("✅ MongoDB connected successfully")
except Exception as e:
    print("❌ MongoDB connection failed:", e)

# -------------------------------------------------------------------
# SUPABASE CONFIG
# -------------------------------------------------------------------
SUPABASE_URL = config("SUPABASE_URL", default="https://vioeqcdpamatksaalpde.supabase.co")
SUPABASE_KEY = config("SUPABASE_KEY", default="your_default_supabase_key")
SUPABASE_BUCKET = config("SUPABASE_BUCKET", default="datasets")

# -------------------------------------------------------------------
# APPLICATIONS
# -------------------------------------------------------------------
INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "corsheaders",

    # Project apps
    "users",
    "datasets",
    "assistant",
]

# -------------------------------------------------------------------
# MIDDLEWARE
# -------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # For static files
    "corsheaders.middleware.CorsMiddleware",       # For API calls
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "datapilot_ai.urls"

# -------------------------------------------------------------------
# TEMPLATES
# -------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "datapilot_ai.wsgi.application"

# -------------------------------------------------------------------
# SQL DATABASE (Django ORM)
# -------------------------------------------------------------------
import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        default=config("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
    )
}

# -------------------------------------------------------------------
# PASSWORD VALIDATION
# -------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------------
# STATIC FILES
# -------------------------------------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# -------------------------------------------------------------------
# PRIMARY KEY DEFAULT
# -------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------------------------------------------------------------------
# AUTH REDIRECTS
# -------------------------------------------------------------------
LOGIN_REDIRECT_URL = "/api/assistant/workspace/"
LOGOUT_REDIRECT_URL = "/users/login/"
LOGIN_URL = "/users/login"

AUTHENTICATION_BACKENDS = [
    "users.mongo_auth_backend.MongoAuthBackend",  # MongoDB login
    "django.contrib.auth.backends.ModelBackend",  # default backend
]

# -------------------------------------------------------------------
# CORS SETTINGS
# -------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default="", cast=Csv())
