"""
Django settings for datapilot_ai project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
from mongoengine import connect

# -------------------------------------------------------------------
# BASE DIRECTORY
# -------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------------------------
# MONGOENGINE CONNECTION (for datasets / documents)
# -------------------------------------------------------------------
# -------------------------------------------------------------------
# MONGOENGINE CONNECTION (for datasets / documents)
# -------------------------------------------------------------------
try:
    connect(
        db="datapilot",
        host="mongodb+srv://shree:xifko4-higpar-dopgyC@cluster0.fhplq.mongodb.net/datapilot?retryWrites=true&w=majority&appName=Cluster0"
    )
    print("✅ MongoDB connected successfully")
except Exception as e:
    print("❌ MongoDB connection failed:", e)
    
import os

SUPABASE_URL = os.environ.get("SUPABASE_URL", "https://vioeqcdpamatksaalpde.supabase.co")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpb2VxY2RwYW1hdGtzYWFscGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NTM0NTksImV4cCI6MjA3ODAyOTQ1OX0.s7hP2wMkQvwRDg5cUS4TDlxSZBIrtjQjZ8MbtKCrthQ")
SUPABASE_BUCKET = "datasets"

# -------------------------------------------------------------------
# SECURITY
# -------------------------------------------------------------------
SECRET_KEY = "django-insecure-rilt(np4nj%5nnab^&)u_qx^flm#7^lim=1lbw+xpg*!lc+b_c"
DEBUG = True
ALLOWED_HOSTS = []

# -------------------------------------------------------------------
# APPLICATIONS
# -------------------------------------------------------------------
INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",

    # Project apps
    "users",
    "datasets",
    "assistant",
]

# -------------------------------------------------------------------
# MIDDLEWARE
# -------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "datapilot_ai.urls"

# -------------------------------------------------------------------
# TEMPLATES
# -------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "datapilot_ai.wsgi.application"

# -------------------------------------------------------------------
# SQL DATABASE (Django ORM)
# -------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# -------------------------------------------------------------------
# PASSWORD VALIDATION
# -------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------------
# STATIC FILES
# -------------------------------------------------------------------
STATIC_URL = "static/"

# -------------------------------------------------------------------
# PRIMARY KEY DEFAULT
# -------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------------------------------------------------------------------
# AUTH REDIRECTS
# -------------------------------------------------------------------
LOGIN_REDIRECT_URL = "/api/assistant/workspace/"

LOGOUT_REDIRECT_URL = "/users/login/"
LOGIN_URL = "/users/login"

AUTHENTICATION_BACKENDS = [
    "users.mongo_auth_backend.MongoAuthBackend",      # our MongoDB login
    "django.contrib.auth.backends.ModelBackend",      # default backend (required!)
]

